<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>48ade9a2-8424-4cff-8e41-7930ed9f54e9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VirtualInterviewee.Application\VirtualInterviewee.Application.csproj" />
    <ProjectReference Include="..\VirtualInterviewee.Infrastructure\VirtualInterviewee.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resume\**\*.pdf" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
